name: qr_vault
description: Scan, create and manage your QR codes easily.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  share_plus: ^10.1.2
  path_provider: ^2.1.4
  screenshot: ^3.0.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  intl: ^0.19.0

flutter:
  uses-material-design: true
